Add docs on continuous deploy (closes #24)
UCSC-CSE123/beavertail pull request #29
Opened 2020-04-25 21:08 UTC by natanlao

2020-04-25 21:11 UTC, penguingovernor commented on README.md
> +     instance, e.g., `username@hostname:portname`. It would probabl be a good
```suggestion
     instance, e.g., `username@hostname:portname`. It would probably be a good
```

2020-04-25 21:15 UTC, penguingovernor requested changes
Small nit (:

2020-04-26 01:45 UTC, penguingovernor approved these changes
lgtm

2020-05-03 06:47 UTC, jennie-n approved these changes

2020-05-04 00:44 UTC, merged